apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: flask-demo-app
    app.kubernetes.io/name: flask-demo-app
    app.kubernetes.io/managed-by: kubectl-apply
  name: flask-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-demo-app
      app.kubernetes.io/managed-by: kubectl-apply
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-demo-app
        app.kubernetes.io/managed-by: kubectl-apply
    spec:
      containers:
        - name: app
          image: flask-demo-app:latest
          imagePullPolicy: IfNotPresent
          args:
            - uwsgi
            - --ini
            - app.ini
            - --need-app
          ports:
            - name: http
              containerPort: 8600
              protocol: TCP
          resources:
            requests:
              memory: 256Mi
              cpu: 0.5
            limits:
              memory: 512Mi
              cpu: 2
          livenessProbe:
            httpGet:
              path: /api/docs/
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /api/docs/
              port: http
              scheme: HTTP
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - SETPCAP
                - NET_BIND_SERVICE
                - NET_RAW
                - SYS_CHROOT
                - MKNOD
                - AUDIT_WRITE
                - SETFCAP
          volumeMounts:
            - name: empty-dir
              mountPath: /opt/local
            - name: app-ini
              mountPath: /home/docker/app/app.ini
              subPath: app.ini
              readOnly: true
      volumes:
        - emptyDir: {}
          name: empty-dir
        - name: app-ini
          projected:
            sources:
              - configMap:
                  name: flask-demo-app
